baseURL = '/'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = 'Traduttori corsu'
theme = "PaperMod"
author = "Paul Franceschi"

[languages]
  [languages.en]
    languageName = "English"
    [[languages.en.menu.main]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "blog"
      name = "Blog"
      pageRef = "/content/pages/blog.md"
      url = "/blog/"
      weight = 2

  [languages.fr]
    languageName = "Français"
    [[languages.fr.menu.main]]
      identifier = "home.fr"
      name = "Accueil"
      pageRef = "/content/_index.fr.md"
      url = "/"
      weight = 1
    [[languages.fr.menu.main]]
      identifier = "blog_fr"
      name = "Blog"
      pageRef = "/content/pages/blog.fr.md"
      url = "/blog_fr/"
      weight = 2

  [languages.co]
    languageName = "Corsu"
    [[languages.co.menu.main]]
      identifier = "home.co"
      name = "Pagina maestra"
      pageRef = "/content/_index.co.md"
      url = "/"
      weight = 1
    [[languages.co.menu.main]]
      identifier = "blog_co"
      name = "Bloggu"
      pageRef = "/content/pages/blog.co.md"
      url = "/blog_co/"
      weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
