baseURL = '/'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = 'Traduttori corsu'
theme = "PaperMod"
author = "Paul Franceschi"

[params]
# Declare "post" as a main section to be included in the home page
mainSections = ["post"]

[languages]
  [languages.en]
    languageName = "English"
    [[languages.en.menu.main]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

  [languages.fr]
    languageName = "Français"
    [[languages.fr.menu.main]]
      identifier = "home.fr"
      name = "Accueil"
      pageRef = "/content/_index.fr.md"
      url = "/"
      weight = 1

  [languages.co]
    languageName = "Corsu"
    [[languages.co.menu.main]]
      identifier = "home.co"
      name = "Pagina maestra"
      pageRef = "/content/_index.co.md"
      url = "/"
      weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
